apiVersion: v1
kind: Secret
metadata:
  name: mediawiki-secret
type: Opaque
stringData:
  db-root-password: "your-root-password"
  db-name: "mediawikidb"
  db-user: "wikiuser"
  db-password: "your-user-password"
